- name: Place file
  hosts: 10.128.15.214
  become: yes

  tasks:

- name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
  ansible.builtin.file:
    path: /tmp/foo.conf
    state: touch
    mode: u=rw,g=r,o=r

