---
- name: Hello World!
  hosts: all

  tasks:

  - name: Download foo.conf
    #ansible.builtin.get_url:
     # url: http://example.com/path/file.conf
     # dest: /etc/foo.conf
    ansible.builtin.file:
      path: /tmp/foo.conf
      state: touch
      mode: u=rw,g=r,o=r
