---
- name: Hello World!
  hosts: all

  tasks:

  - name: Hello World!
  - name: Download foo.conf
    ansible.builtin.get_url:
      url: http://example.com/path/file.conf
      dest: /etc/foo.conf
